/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AgentRegistry {
      
    export type AgentInfoStruct = {capabilities: string, reputation: BigNumberish, stake: BigNumberish, active: boolean}

    export type AgentInfoStructOutput = [capabilities: string, reputation: bigint, stake: bigint, active: boolean] & {capabilities: string, reputation: bigint, stake: bigint, active: boolean }
  
    }

  export interface AgentRegistryInterface extends Interface {
    getFunction(nameOrSignature: "agents" | "deregister" | "getAgent" | "minStake" | "owner" | "register" | "updateReputation"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentDeregistered" | "AgentRegistered" | "ReputationUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'agents', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deregister', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAgent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'minStake', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'register', values: [string]): string;
encodeFunctionData(functionFragment: 'updateReputation', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'agents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deregister', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'register', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateReputation', data: BytesLike): Result;
  }

  
    export namespace AgentDeregisteredEvent {
      export type InputTuple = [agent: AddressLike];
      export type OutputTuple = [agent: string];
      export interface OutputObject {agent: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentRegisteredEvent {
      export type InputTuple = [agent: AddressLike, capabilities: string];
      export type OutputTuple = [agent: string, capabilities: string];
      export interface OutputObject {agent: string, capabilities: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationUpdatedEvent {
      export type InputTuple = [agent: AddressLike, newReputation: BigNumberish];
      export type OutputTuple = [agent: string, newReputation: bigint];
      export interface OutputObject {agent: string, newReputation: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentRegistry;
    waitForDeployment(): Promise<this>;

    interface: AgentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    agents: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, boolean] & {capabilities: string, reputation: bigint, stake: bigint, active: boolean }],
      'view'
    >
    

    
    deregister: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getAgent: TypedContractMethod<
      [agent: AddressLike, ],
      [AgentRegistry.AgentInfoStructOutput],
      'view'
    >
    

    
    minStake: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    register: TypedContractMethod<
      [capabilities: string, ],
      [void],
      'payable'
    >
    

    
    updateReputation: TypedContractMethod<
      [agent: AddressLike, newReputation: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'agents'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, boolean] & {capabilities: string, reputation: bigint, stake: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'deregister'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAgent'): TypedContractMethod<
      [agent: AddressLike, ],
      [AgentRegistry.AgentInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'minStake'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'register'): TypedContractMethod<
      [capabilities: string, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'updateReputation'): TypedContractMethod<
      [agent: AddressLike, newReputation: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgentDeregistered'): TypedContractEvent<AgentDeregisteredEvent.InputTuple, AgentDeregisteredEvent.OutputTuple, AgentDeregisteredEvent.OutputObject>;
getEvent(key: 'AgentRegistered'): TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
getEvent(key: 'ReputationUpdated'): TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;

    filters: {
      
      'AgentDeregistered(address)': TypedContractEvent<AgentDeregisteredEvent.InputTuple, AgentDeregisteredEvent.OutputTuple, AgentDeregisteredEvent.OutputObject>;
      AgentDeregistered: TypedContractEvent<AgentDeregisteredEvent.InputTuple, AgentDeregisteredEvent.OutputTuple, AgentDeregisteredEvent.OutputObject>;
    

      'AgentRegistered(address,string)': TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
      AgentRegistered: TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
    

      'ReputationUpdated(address,uint256)': TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
      ReputationUpdated: TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
    
    };
  }