/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PaymentChannel {
      
    export type TaskStruct = {requester: AddressLike, provider: AddressLike, amount: BigNumberish, deadline: BigNumberish, settled: boolean}

    export type TaskStructOutput = [requester: string, provider: string, amount: bigint, deadline: bigint, settled: boolean] & {requester: string, provider: string, amount: bigint, deadline: bigint, settled: boolean }
  
    }

  export interface PaymentChannelInterface extends Interface {
    getFunction(nameOrSignature: "auditor" | "forceRelease" | "getTask" | "lock" | "refund" | "release" | "tasks"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentLocked" | "PaymentRefunded" | "PaymentReleased"): EventFragment;

    encodeFunctionData(functionFragment: 'auditor', values?: undefined): string;
encodeFunctionData(functionFragment: 'forceRelease', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getTask', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'lock', values: [BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'refund', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'release', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'tasks', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'auditor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'forceRelease', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'release', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tasks', data: BytesLike): Result;
  }

  
    export namespace PaymentLockedEvent {
      export type InputTuple = [taskId: BytesLike, requester: AddressLike, provider: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, requester: string, provider: string, amount: bigint];
      export interface OutputObject {taskId: string, requester: string, provider: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentRefundedEvent {
      export type InputTuple = [taskId: BytesLike, requester: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, requester: string, amount: bigint];
      export interface OutputObject {taskId: string, requester: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentReleasedEvent {
      export type InputTuple = [taskId: BytesLike, provider: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, provider: string, amount: bigint];
      export interface OutputObject {taskId: string, provider: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PaymentChannel extends BaseContract {
    
    connect(runner?: ContractRunner | null): PaymentChannel;
    waitForDeployment(): Promise<this>;

    interface: PaymentChannelInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    auditor: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    forceRelease: TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getTask: TypedContractMethod<
      [taskId: BytesLike, ],
      [PaymentChannel.TaskStructOutput],
      'view'
    >
    

    
    lock: TypedContractMethod<
      [taskId: BytesLike, provider: AddressLike, deadline: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    refund: TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    release: TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    tasks: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, boolean] & {requester: string, provider: string, amount: bigint, deadline: bigint, settled: boolean }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'auditor'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'forceRelease'): TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTask'): TypedContractMethod<
      [taskId: BytesLike, ],
      [PaymentChannel.TaskStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'lock'): TypedContractMethod<
      [taskId: BytesLike, provider: AddressLike, deadline: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'release'): TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tasks'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, boolean] & {requester: string, provider: string, amount: bigint, deadline: bigint, settled: boolean }],
      'view'
    >;

    getEvent(key: 'PaymentLocked'): TypedContractEvent<PaymentLockedEvent.InputTuple, PaymentLockedEvent.OutputTuple, PaymentLockedEvent.OutputObject>;
getEvent(key: 'PaymentRefunded'): TypedContractEvent<PaymentRefundedEvent.InputTuple, PaymentRefundedEvent.OutputTuple, PaymentRefundedEvent.OutputObject>;
getEvent(key: 'PaymentReleased'): TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;

    filters: {
      
      'PaymentLocked(bytes32,address,address,uint256)': TypedContractEvent<PaymentLockedEvent.InputTuple, PaymentLockedEvent.OutputTuple, PaymentLockedEvent.OutputObject>;
      PaymentLocked: TypedContractEvent<PaymentLockedEvent.InputTuple, PaymentLockedEvent.OutputTuple, PaymentLockedEvent.OutputObject>;
    

      'PaymentRefunded(bytes32,address,uint256)': TypedContractEvent<PaymentRefundedEvent.InputTuple, PaymentRefundedEvent.OutputTuple, PaymentRefundedEvent.OutputObject>;
      PaymentRefunded: TypedContractEvent<PaymentRefundedEvent.InputTuple, PaymentRefundedEvent.OutputTuple, PaymentRefundedEvent.OutputObject>;
    

      'PaymentReleased(bytes32,address,uint256)': TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
      PaymentReleased: TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
    
    };
  }