/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ResultAttestation {
      
    export type AttestationStruct = {provider: AddressLike, resultHash: BytesLike, timestamp: BigNumberish, disputed: boolean}

    export type AttestationStructOutput = [provider: string, resultHash: string, timestamp: bigint, disputed: boolean] & {provider: string, resultHash: string, timestamp: bigint, disputed: boolean }
  
    }

  export interface ResultAttestationInterface extends Interface {
    getFunction(nameOrSignature: "attest" | "attestations" | "dispute" | "getAttestation"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ResultAttested" | "ResultDisputed"): EventFragment;

    encodeFunctionData(functionFragment: 'attest', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'attestations', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'dispute', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getAttestation', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'attest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attestations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAttestation', data: BytesLike): Result;
  }

  
    export namespace ResultAttestedEvent {
      export type InputTuple = [taskId: BytesLike, provider: AddressLike, resultHash: BytesLike];
      export type OutputTuple = [taskId: string, provider: string, resultHash: string];
      export interface OutputObject {taskId: string, provider: string, resultHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ResultDisputedEvent {
      export type InputTuple = [taskId: BytesLike, disputedBy: AddressLike];
      export type OutputTuple = [taskId: string, disputedBy: string];
      export interface OutputObject {taskId: string, disputedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ResultAttestation extends BaseContract {
    
    connect(runner?: ContractRunner | null): ResultAttestation;
    waitForDeployment(): Promise<this>;

    interface: ResultAttestationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attest: TypedContractMethod<
      [taskId: BytesLike, resultHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    attestations: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, boolean] & {provider: string, resultHash: string, timestamp: bigint, disputed: boolean }],
      'view'
    >
    

    
    dispute: TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getAttestation: TypedContractMethod<
      [taskId: BytesLike, ],
      [ResultAttestation.AttestationStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attest'): TypedContractMethod<
      [taskId: BytesLike, resultHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'attestations'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, boolean] & {provider: string, resultHash: string, timestamp: bigint, disputed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'dispute'): TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAttestation'): TypedContractMethod<
      [taskId: BytesLike, ],
      [ResultAttestation.AttestationStructOutput],
      'view'
    >;

    getEvent(key: 'ResultAttested'): TypedContractEvent<ResultAttestedEvent.InputTuple, ResultAttestedEvent.OutputTuple, ResultAttestedEvent.OutputObject>;
getEvent(key: 'ResultDisputed'): TypedContractEvent<ResultDisputedEvent.InputTuple, ResultDisputedEvent.OutputTuple, ResultDisputedEvent.OutputObject>;

    filters: {
      
      'ResultAttested(bytes32,address,bytes32)': TypedContractEvent<ResultAttestedEvent.InputTuple, ResultAttestedEvent.OutputTuple, ResultAttestedEvent.OutputObject>;
      ResultAttested: TypedContractEvent<ResultAttestedEvent.InputTuple, ResultAttestedEvent.OutputTuple, ResultAttestedEvent.OutputObject>;
    

      'ResultDisputed(bytes32,address)': TypedContractEvent<ResultDisputedEvent.InputTuple, ResultDisputedEvent.OutputTuple, ResultDisputedEvent.OutputObject>;
      ResultDisputed: TypedContractEvent<ResultDisputedEvent.InputTuple, ResultDisputedEvent.OutputTuple, ResultDisputedEvent.OutputObject>;
    
    };
  }