services:
  - type: web
    name: maep-cn
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_PATH
        value: /opt/render/project/src/maep.db
      - key: PYTHON_VERSION
        value: 3.11.0
